version: '3.3'

services:
  app-build:
    build: .
    image: icc-erm:latest
    environment:
      - NUXT_APP_BASE_URL=/icc-erm/
    ports:
      - "9020:3000"
    env_file:
      - .env
    command: ["node", ".output/server/index.mjs"]
    restart: always