name: Deploy Nuxt App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Set up SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host sssh.rsiap.my.id" >> ~/.ssh/config
        echo "  ProxyCommand cloudflared access ssh --hostname sssh.rsiap.my.id" >> ~/.ssh/config

    - name: Deploy application
      run: ssh -o StrictHostKeyChecking=no $SSH_USER@sssh.rsiap.my.id "bash /var/www/html/JsApp/icc/build.sh"
