name: Deploy Nuxt App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Set up SSH and SSH Agent
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host sssh.rsiap.my.id" >> ~/.ssh/config
        echo "  ProxyCommand cloudflared access ssh --hostname %h" >> ~/.ssh/config
        
        # Start the SSH agent and add the key with passphrase
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@sssh.rsiap.my.id \
          "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S bash /var/www/html/JsApp/icc/build.sh"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        SSH_USER: ${{ secrets.SSH_USER }}
